# Generated by Django 5.2.6 on 2025-09-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "jobtype",
                    models.CharField(
                        choices=[("onsite", "Onsite"), ("remote", "Remote")],
                        max_length=20,
                    ),
                ),
                (
                    "jobtime",
                    models.CharField(
                        choices=[
                            ("full-time", "Full-Time"),
                            ("part-time", "Part-Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("shift", models.CharField(blank=True, max_length=50, null=True)),
                ("required_skills", models.TextField()),
                ("domain", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
